apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-server
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
    
